# --- MONITOR ---
monitor=WAYLAND-1,highres,0x0,1

# --- NO ANIME IN THIS ROOM ---
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

# --- WORKSPACES BTCH ---

plugin {
    hyprexpo{
	columns = 3
	gap_size = 5
	bg_col = rgb(1a1a1a)
	workspace_method = center current # [center [visiting, dual, selection] ornaments]

	#enable_gesture = false
	#gesture_fingers = 3
	#gesture_distance = 300

	active_border = rgb(fa0567)
	inactive_border = rgb(73022f)
    }
}

# --- AUTOSTART ---
exec-once = waybar > /dev/null 2>&1 & awww-daemon && awww img ~/dotfiles/wallpapers/THAhando.jpeg & hyprpm reload

# --- INPUT ---
binds {
    allow_workspace_cycles = true
    focus_preferred_method = 0
}          

input { 
    kb_layout = us 
    follow_mouse = 1
    # Higher delay means you have to hold a key longer before it repeats
    repeat_delay = 600 
    # Lower rate means it repeats slower
    repeat_rate = 20
    
}

# --- STYLE (The "Creation" Part) ---
general { 
    gaps_in = 5 # Space between windows 
    gaps_out = 8  # Space between windows and screen edge 
    border_size = 0 
    col.active_border = rgba(a00342ff) 
    col.inactive_border = rgba(a00342ff)
}

# --- THE CONTROL DECK ---
$mainMod = SUPER

# Overview
bind = SUPER, Tab, hyprexpo:expo, toggle
bind = SUPER, mouse:274, hyprexpo:expo, toggle

# Win + Numpad 7 = Open Terminal (Foot)
bind = $mainMod, KP_Home, exec, foot

# Win + Numpad 8 = Open App Menu (Wofi)
bind = $mainMod, KP_Up, exec, wofi --show drun

# Win + Numpad 9 = Close Window
bind = $mainMod, KP_Prior, killactive,

# Win + Numpad 0 = Emergency Exit System
bind = $mainMod, KP_Insert, exit,

# --- CLIPBOARD ---
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# --- CLIPHISTORY ---
bind = SUPER, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy

# --- THE VIBE (Decoration) ---
decoration { 
    rounding = 6           # Smooth rounded corners 
    active_opacity = 1  # 10% transparent when active 
    inactive_opacity = 0.6 # 30% transparent when in background

    blur { 
        enabled = true size = 4 # How blurry it is 
        passes = 2 # Smoothing quality 
        new_optimizations = true
    }

# --- NEW SYNTAX FOR SHADOWS ---
    shadow {
        enabled = false
        range = 8
        render_power = 3
        color = rgba(a3005aff)
    }
}

# --- BADBARS(Decoration) ---
plugin {
    hyprbars {
        bar_height = 25
        bar_color = rgb(73022f)
        col.text = rgb(ffffff)
	
	bar_part_of_window = true

	bar_text_font = JetBrainsMono Nerd Font
        bar_text_size = 8

        hyprbars-button = rgb(fa0567), 10, 󰖭 , hyprctl dispatch killactive #CLOSE
	hyprbars-button = rgb(fa0567), 10,  , hyprctl dispatch fullscreen 1  #SCALE
	hyprbars-button = rgb(fa0567), 10,  , hyprctl dispatch movetoworkspacesilent special #HIDE
    }
}

